---
title: "GLMM and GLM Analysis"
author: "Rui Carvalho"
output:
  html_document:
    theme: united
    highlight: tango
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: no
      smooth_scroll: no
---

```{r setup, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
options(knitr.table.format = "html")

```


# Preparing files

## Libraries 

``` {r, results ='hide'}  
library(BAT)
library(readr)
library(FD) 
library(car)
library(MASS)
library(lme4)
library(here)       # to locate files
library(data.table) # to work with data
library(dplyr)      # to manage data
library(magrittr)   # to use the pipe operator %>% 
library(MuMIn)
```


## Calling results dataset

```{r}
Results2 <- read.csv2(here("results","RESULTS.CSV"), header=TRUE, row.names = 1,  stringsAsFactors = T,sep = ",", dec = ".")
str(Results2)
```

## Checking for colinearity 

```{r}
results.variables <- Results2[,5:8] # selecting the variables relevant to the test

numeric.results.variables <- Results2[,6:8] # selecting the variables relevant to the test
cor(numeric.results.variables)  #isto ontem funcionava, não sei o que se passa
```

## Generating the models
```{r}

gm1 <- glmer(TAlphaAll ~ Dist_edge_std + Treatment + Dist_trail_std + Dist_trail_beginning_std + (1 | ForestID), data = Results2 , family = poisson)
options(na.action = "na.fail")
dredge(gm1,evaluate=FALSE)
```

## Model comparison table
```{r}
dredge(gm1, extra = c("R^2", F = function(x)
    summary(x)$fstatistic[[1]]))

# Returns Values unranked: "(Int) / ESTIMATE(Dst_edg /Dst_trl /Dst_trl_bgn/ Trt) / R^2 /df / logLik  /AICc/ delta/ weight"

#options(na.action = "na.omit")

```


